brew cask install font-3270
brew cask install font-abeezee
brew cask install font-abel
brew cask install font-aboriginal-sans
brew cask install font-aboriginal-serif
brew cask install font-abril-fatface
brew cask install font-acme
brew cask install font-actor
brew cask install font-adamina
brew cask install font-adinatha-tamil-brahmi
brew cask install font-advent-pro
brew cask install font-african-sans
brew cask install font-african-serif
brew cask install font-aguafina-script
brew cask install font-ahuramzda
brew cask install font-aileron
brew cask install font-akronim
brew cask install font-aladin
brew cask install font-aldrich
brew cask install font-alef
brew cask install font-alegreya-sans-sc
brew cask install font-alegreya-sans
brew cask install font-alegreya-sc
brew cask install font-alegreya
brew cask install font-aleo
brew cask install font-alex-brush
brew cask install font-alfa-slab-one
brew cask install font-alice
brew cask install font-alike-angular
brew cask install font-alike
brew cask install font-allan
brew cask install font-allerta-stencil
brew cask install font-allerta
brew cask install font-allura
brew cask install font-almendra-display
brew cask install font-almendra-sc
brew cask install font-almendra
brew cask install font-amarante
brew cask install font-amaranth
brew cask install font-amatic-sc
brew cask install font-amethysta
brew cask install font-amiri
brew cask install font-anaheim
brew cask install font-andada-sc
brew cask install font-andada
brew cask install font-andagii
brew cask install font-andale-mono
brew cask install font-andika
brew cask install font-anka-coder
brew cask install font-anonymice-powerline
brew cask install font-anonymous-pro
brew cask install font-antic-didone
brew cask install font-antic-slab
brew cask install font-antic
brew cask install font-antinoou
brew cask install font-anton
brew cask install font-arapey
brew cask install font-arbutus-slab
brew cask install font-arbutus
brew cask install font-archivo-black
brew cask install font-archivo-narrow
brew cask install font-arial-black
brew cask install font-arial
brew cask install font-arimo
brew cask install font-arizonia
brew cask install font-armata
brew cask install font-artifika
brew cask install font-arvo
brew cask install font-asap
brew cask install font-astloch
brew cask install font-asul
brew cask install font-atomic-age
brew cask install font-aubrey
brew cask install font-audiowide
brew cask install font-autour-one
brew cask install font-average
brew cask install font-averia-gruesa-libre
brew cask install font-averia-libre
brew cask install font-averia-sans-libre
brew cask install font-averia-serif-libre
brew cask install font-awesome-terminal-fonts
brew cask install font-babelstone-han
brew cask install font-bad-script
brew cask install font-baloo
brew cask install font-balthazar
brew cask install font-bangers
brew cask install font-baron
brew cask install font-basic
brew cask install font-battambang
brew cask install font-baumans
brew cask install font-bebas-neue
brew cask install font-belgrano
brew cask install font-belleza
brew cask install font-benchnine
brew cask install font-bentham
brew cask install font-berkshire-swash
brew cask install font-bevan
brew cask install font-bf-tiny-hand
brew cask install font-bigelow-rules
brew cask install font-bilbo-swash-caps
brew cask install font-bilbo
brew cask install font-bitstream-vera
brew cask install font-bitter
brew cask install font-black-ops-one
brew cask install font-blokk-neue
brew cask install font-bonbon
brew cask install font-boogaloo
brew cask install font-bowlby-one-sc
brew cask install font-bowlby-one
brew cask install font-bravura
brew cask install font-brawler
brew cask install font-bree-serif
brew cask install font-bubblegum-sans
brew cask install font-bubbler-one
brew cask install font-buda
brew cask install font-buenard
brew cask install font-bukyvede-bold
brew cask install font-bukyvede-italic
brew cask install font-bukyvede-regular
brew cask install font-bungee
brew cask install font-butcherman
brew cask install font-butler
brew cask install font-butterfly-kids
brew cask install font-cabin-condensed
brew cask install font-cabin-sketch
brew cask install font-cabin
brew cask install font-caesar-dressing
brew cask install font-cagliostro
brew cask install font-calligraffitti
brew cask install font-cambo
brew cask install font-camingocode
brew cask install font-candal
brew cask install font-cantarell
brew cask install font-cantata-one
brew cask install font-canter
brew cask install font-cantora-one
brew cask install font-capriola
brew cask install font-cardo
brew cask install font-carme
brew cask install font-carrois-gothic-sc
brew cask install font-carrois-gothic
brew cask install font-carter-one
brew cask install font-caudex
brew cask install font-cedarville-cursive
brew cask install font-ceviche-one
brew cask install font-changa-one
brew cask install font-chango
brew cask install font-chapbook
brew cask install font-charis-sil
brew cask install font-charter
brew cask install font-chau-philomene-one
brew cask install font-chela-one
brew cask install font-chelsea-market
brew cask install font-chenla
brew cask install font-cherry-swash
brew cask install font-chicle
brew cask install font-chivo
brew cask install font-cinzel-decorative
brew cask install font-cinzel
brew cask install font-clear-sans
brew cask install font-clicker-script
brew cask install font-coda
brew cask install font-code
brew cask install font-code2000
brew cask install font-code2001
brew cask install font-code2002
brew cask install font-codystar
brew cask install font-combo
brew cask install font-comfortaa
brew cask install font-comic-neue
brew cask install font-comic-sans-ms
brew cask install font-computer-modern
brew cask install font-conakry
brew cask install font-concert-one
brew cask install font-condiment
brew cask install font-consolas-for-powerline
brew cask install font-content
brew cask install font-contrail-one
brew cask install font-convergence
brew cask install font-cookie
brew cask install font-copse
brew cask install font-corben
brew cask install font-courgette
brew cask install font-courier-new
brew cask install font-courier-prime
brew cask install font-cousine
brew cask install font-coustard
brew cask install font-covered-by-your-grace
brew cask install font-creepster
brew cask install font-crete-round
brew cask install font-crimson-text
brew cask install font-croissant-one
brew cask install font-cuprum
brew cask install font-cutive-mono
brew cask install font-cutive
brew cask install font-cwtex-q
brew cask install font-d2coding
brew cask install font-damion
brew cask install font-dancing-script
brew cask install font-dangrek
brew cask install font-dashicons
brew cask install font-dawning-of-a-new-day
brew cask install font-days-one
brew cask install font-dejavu-sans-mono-for-powerline
brew cask install font-dejavu-sans
brew cask install font-delius-swash-caps
brew cask install font-delius-unicase
brew cask install font-delius
brew cask install font-della-respira
brew cask install font-denk-one
brew cask install font-devicons
brew cask install font-devonshire
brew cask install font-dhyana
brew cask install font-digohweli-old-do
brew cask install font-digohweli
brew cask install font-diplomata-sc
brew cask install font-diplomata
brew cask install font-disclaimer
brew cask install font-domine
brew cask install font-donegal-one
brew cask install font-doppio-one
brew cask install font-dorsa
brew cask install font-dosis
brew cask install font-dr-sugiyama
brew cask install font-droid-arabic-kufi
brew cask install font-droid-arabic-naskh
brew cask install font-droid-sans-ethiopic
brew cask install font-droid-sans-mono-for-powerline
brew cask install font-droid-sans-mono
brew cask install font-droid-sans-tamil
brew cask install font-droid-sans-thai
brew cask install font-droid-sans
brew cask install font-droid-serif-thai
brew cask install font-droid-serif
brew cask install font-dukor
brew cask install font-duru-sans
brew cask install font-dynalight
brew cask install font-eagle-lake
brew cask install font-eater
brew cask install font-eb-garamond
brew cask install font-economica
brew cask install font-edlo
brew cask install font-eeyek-unicode
brew cask install font-electrolize
brew cask install font-elsie-swash-caps
brew cask install font-elsie
brew cask install font-emblema-one
brew cask install font-emilys-candy
brew cask install font-engagement
brew cask install font-englebert
brew cask install font-enriqueta
brew cask install font-erica-one
brew cask install font-esteban
brew cask install font-et-book
brew cask install font-euphoria-script
brew cask install font-everson-mono
brew cask install font-ewert
brew cask install font-exo
brew cask install font-exo2
brew cask install font-expletus-sans
brew cask install font-ezra-sil
brew cask install font-fantasque-sans-mono
brew cask install font-fanwood-text
brew cask install font-fascinate-inline
brew cask install font-fascinate
brew cask install font-faster-one
brew cask install font-fasthand
brew cask install font-fauna-one
brew cask install font-federant
brew cask install font-federo
brew cask install font-felipa
brew cask install font-fenix
brew cask install font-finger-paint
brew cask install font-fira-code
brew cask install font-fira-mono-for-powerline
brew cask install font-fira-mono
brew cask install font-fira-sans
brew cask install font-firacode-nerd-font-mono
brew cask install font-firacode-nerd-font
brew cask install font-fjalla-one
brew cask install font-fjord-one
brew cask install font-flamenco
brew cask install font-flavors
brew cask install font-fondamento
brew cask install font-fontawesome
brew cask install font-forum
brew cask install font-foundation-icons
brew cask install font-francois-one
brew cask install font-freckle-face
brew cask install font-fredericka-the-great
brew cask install font-fredoka-one
brew cask install font-free-hk-kai
brew cask install font-freehand
brew cask install font-freesans
brew cask install font-fresca
brew cask install font-frijole
brew cask install font-fruktur
brew cask install font-fugaz-one
brew cask install font-gabriela
brew cask install font-gafata
brew cask install font-galdeano
brew cask install font-galindo
brew cask install font-gandom
brew cask install font-genjyuugothic-l
brew cask install font-genjyuugothic-x
brew cask install font-genjyuugothic
brew cask install font-genshingothic
brew cask install font-gentium-basic
brew cask install font-gentium-book-basic
brew cask install font-gentium-plus
brew cask install font-geo
brew cask install font-georgia
brew cask install font-geostar-fill
brew cask install font-geostar
brew cask install font-germania-one
brew cask install font-gfs-didot
brew cask install font-gfs-neohellenic
brew cask install font-gidole
brew cask install font-gilda-display
brew cask install font-give-you-glory
brew cask install font-glass-antiqua
brew cask install font-glegoo
brew cask install font-glober
brew cask install font-gloria-hallelujah
brew cask install font-gnu-unifont
brew cask install font-go-medium
brew cask install font-go-mono
brew cask install font-go
brew cask install font-goblin-one
brew cask install font-gochi-hand
brew cask install font-gorditas
brew cask install font-goudy-bookletter1911
brew cask install font-graduate
brew cask install font-grand-hotel
brew cask install font-gravitas-one
brew cask install font-great-vibes
brew cask install font-griffy
brew cask install font-gruppo
brew cask install font-gudea
brew cask install font-habibi
brew cask install font-hack-nerd-font
brew cask install font-hack
brew cask install font-halant
brew cask install font-hammersmith-one
brew cask install font-han-nom-a
brew cask install font-hanalei-fill
brew cask install font-hanalei
brew cask install font-hanamina
brew cask install font-handlee
brew cask install font-hanuman
brew cask install font-happy-monkey
brew cask install font-hasklig
brew cask install font-headland-one
brew cask install font-henny-penny
brew cask install font-hermeneus-one
brew cask install font-hermit
brew cask install font-herr-von-muellerhoff
brew cask install font-hind
brew cask install font-holtwood-one-sc
brew cask install font-homenaje
brew cask install font-hyppolit
brew cask install font-iceberg
brew cask install font-iceland
brew cask install font-icomoon
brew cask install font-idealist-sans
brew cask install font-im-fell-double-pica-sc
brew cask install font-im-fell-double-pica
brew cask install font-im-fell-dw-pica-sc
brew cask install font-im-fell-dw-pica
brew cask install font-im-fell-english-sc
brew cask install font-im-fell-english
brew cask install font-im-fell-french-canon-sc
brew cask install font-im-fell-french-canon
brew cask install font-im-fell-great-primer-sc
brew cask install font-im-fell-great-primer
brew cask install font-impact
brew cask install font-imprima
brew cask install font-inconsolata-dz-for-powerline
brew cask install font-inconsolata-dz
brew cask install font-inconsolata-for-powerline
brew cask install font-inconsolata-g-for-powerline
brew cask install font-inconsolata-lgc
brew cask install font-inconsolata
brew cask install font-inder
brew cask install font-indie-flower
brew cask install font-inika
brew cask install font-input
brew cask install font-ionicons
brew cask install font-iosevka
brew cask install font-iranian-sans
brew cask install font-iranian-serif
brew cask install font-istok-web
brew cask install font-italiana
brew cask install font-italianno
brew cask install font-jaapokki
brew cask install font-jacques-francois-shadow
brew cask install font-jacques-francois
brew cask install font-jim-nightshade
brew cask install font-jockey-one
brew cask install font-jolly-lodger
brew cask install font-josefin-sans
brew cask install font-josefin-slab
brew cask install font-joti-one
brew cask install font-jsmath-cmbx10
brew cask install font-judson
brew cask install font-julee
brew cask install font-julius-sans-one
brew cask install font-junge
brew cask install font-jura
brew cask install font-just-me-again-down-here
brew cask install font-kacstone
brew cask install font-kalam
brew cask install font-kameron
brew cask install font-kantumruy
brew cask install font-karla-tamil-inclined
brew cask install font-karla-tamil-upright
brew cask install font-karla
brew cask install font-karma
brew cask install font-kaushan-script
brew cask install font-kavoon
brew cask install font-kawkab-mono
brew cask install font-kayases
brew cask install font-kdam-thmor
brew cask install font-keania-one
brew cask install font-keep-calm
brew cask install font-kelly-slab
brew cask install font-kenia
brew cask install font-khand
brew cask install font-khmer
brew cask install font-kisiska
brew cask install font-kite-one
brew cask install font-knewave
brew cask install font-koruri
brew cask install font-kotta-one
brew cask install font-koulen
brew cask install font-kreon
brew cask install font-krona-one
brew cask install font-la-belle-aurore
brew cask install font-laila
brew cask install font-lalezar
brew cask install font-lancelot
brew cask install font-lateef
brew cask install font-latin-modern-math
brew cask install font-latin-modern
brew cask install font-lato
brew cask install font-league-gothic
brew cask install font-league-script
brew cask install font-league-spartan
brew cask install font-leckerli-one
brew cask install font-ledger
brew cask install font-lekton
brew cask install font-lemon
brew cask install font-liberation-mono-for-powerline
brew cask install font-liberation-sans
brew cask install font-libertinus
brew cask install font-libre-baskerville
brew cask install font-libre-caslon-text
brew cask install font-libre-franklin
brew cask install font-life-savers
brew cask install font-ligature-symbols
brew cask install font-lilita-one
brew cask install font-lily-script-one
brew cask install font-limelight
brew cask install font-linden-hill
brew cask install font-linux-biolinum
brew cask install font-linux-libertine
brew cask install font-lisutzimu
brew cask install font-lobster-two
brew cask install font-lobster
brew cask install font-lohit-tamil-classical
brew cask install font-lohit-tamil
brew cask install font-lohit-telugu
brew cask install font-londrina-outline
brew cask install font-londrina-shadow
brew cask install font-londrina-sketch
brew cask install font-londrina-solid
brew cask install font-lora
brew cask install font-love-ya-like-a-sister
brew cask install font-loved-by-the-king
brew cask install font-lovers-quarrel
brew cask install font-luculent
brew cask install font-lusitana
brew cask install font-lustria
brew cask install font-m-plus
brew cask install font-macondo-swash-caps
brew cask install font-macondo
brew cask install font-magra
brew cask install font-mako
brew cask install font-marcellus-sc
brew cask install font-marcellus
brew cask install font-marck-script
brew cask install font-margarine
brew cask install font-marko-one
brew cask install font-marmelad
brew cask install font-marta
brew cask install font-marvel
brew cask install font-masinahikan-dene
brew cask install font-masinahikan
brew cask install font-mate-sc
brew cask install font-mate
brew cask install font-material-icons
brew cask install font-materialdesignicons-webfont
brew cask install font-maven-pro
brew cask install font-mclaren
brew cask install font-meddon
brew cask install font-medievalsharp
brew cask install font-medula-one
brew cask install font-megrim
brew cask install font-meie-script
brew cask install font-menlo-for-powerline
brew cask install font-merienda-one
brew cask install font-merienda
brew cask install font-merriweather-sans
brew cask install font-merriweather
brew cask install font-metal
brew cask install font-metamorphous
brew cask install font-metrophobic
brew cask install font-mfizz
brew cask install font-miao-unicode
brew cask install font-michroma
brew cask install font-migmix-1m
brew cask install font-migmix-1p
brew cask install font-migmix-2m
brew cask install font-migmix-2p
brew cask install font-migu-1c
brew cask install font-migu-1m
brew cask install font-migu-1p
brew cask install font-migu-2m
brew cask install font-milonga
brew cask install font-miltonian-tattoo
brew cask install font-miltonian
brew cask install font-miniver
brew cask install font-miss-fajardose
brew cask install font-modern-antiqua
brew cask install font-molengo
brew cask install font-molle
brew cask install font-monda
brew cask install font-monofett
brew cask install font-monofur-for-powerline
brew cask install font-monofur
brew cask install font-monoid
brew cask install font-monoisome
brew cask install font-mononoki
brew cask install font-monoton
brew cask install font-monsieur-la-doulaise
brew cask install font-montaga
brew cask install font-montez
brew cask install font-montserrat-subrayada
brew cask install font-montserrat
brew cask install font-moul
brew cask install font-moulpali
brew cask install font-mountains-of-christmas
brew cask install font-mouse-memoirs
brew cask install font-mr-bedfort
brew cask install font-mr-dafoe
brew cask install font-mr-de-haviland
brew cask install font-mrs-saint-delafield
brew cask install font-mrs-sheppards
brew cask install font-mukti-narrow
brew cask install font-muli
brew cask install font-myrica
brew cask install font-myricam
brew cask install font-mystery-quest
brew cask install font-n-gage
brew cask install font-namdhinggo-sil
brew cask install font-nanumgothic
brew cask install font-nanumgothiccoding
brew cask install font-nanummyeongjo
brew cask install font-neucha
brew cask install font-neuton
brew cask install font-new-athena-unicode
brew cask install font-new-rocker
brew cask install font-news-cycle
brew cask install font-nexa
brew cask install font-niconne
brew cask install font-nika
brew cask install font-nixie-one
brew cask install font-nobile
brew cask install font-nokora
brew cask install font-norican
brew cask install font-norwester
brew cask install font-nosifer
brew cask install font-nothing-you-could-do
brew cask install font-noticia-text
brew cask install font-noto-color-emoji
brew cask install font-noto-emoji
brew cask install font-noto-kufi-arabic
brew cask install font-noto-mono
brew cask install font-noto-naskh-arabic
brew cask install font-noto-nastaliq-urdu
brew cask install font-noto-sans-armenian
brew cask install font-noto-sans-avestan
brew cask install font-noto-sans-balinese
brew cask install font-noto-sans-bamum
brew cask install font-noto-sans-batak
brew cask install font-noto-sans-bengali
brew cask install font-noto-sans-brahmi
brew cask install font-noto-sans-buginese
brew cask install font-noto-sans-buhid
brew cask install font-noto-sans-canadian-aboriginal
brew cask install font-noto-sans-carian
brew cask install font-noto-sans-cham
brew cask install font-noto-sans-cherokee
brew cask install font-noto-sans-cjk-jp
brew cask install font-noto-sans-cjk-kr
brew cask install font-noto-sans-cjk-sc
brew cask install font-noto-sans-cjk-tc
brew cask install font-noto-sans-cjk
brew cask install font-noto-sans-coptic
brew cask install font-noto-sans-cuneiform
brew cask install font-noto-sans-cypriot
brew cask install font-noto-sans-deseret
brew cask install font-noto-sans-devanagari
brew cask install font-noto-sans-egyptian-hieroglyphs
brew cask install font-noto-sans-ethiopic
brew cask install font-noto-sans-georgian
brew cask install font-noto-sans-glagolitic
brew cask install font-noto-sans-gothic
brew cask install font-noto-sans-gujarati
brew cask install font-noto-sans-gurmukhi
brew cask install font-noto-sans-hanunoo
brew cask install font-noto-sans-hebrew
brew cask install font-noto-sans-imperial-aramaic
brew cask install font-noto-sans-inscriptional-pahlavi
brew cask install font-noto-sans-inscriptional-parthian
brew cask install font-noto-sans-javanese
brew cask install font-noto-sans-kaithi
brew cask install font-noto-sans-kannada
brew cask install font-noto-sans-kayah-li
brew cask install font-noto-sans-kharoshthi
brew cask install font-noto-sans-khmer
brew cask install font-noto-sans-lao
brew cask install font-noto-sans-lepcha
brew cask install font-noto-sans-limbu
brew cask install font-noto-sans-linear-b
brew cask install font-noto-sans-lisu
brew cask install font-noto-sans-lycian
brew cask install font-noto-sans-lydian
brew cask install font-noto-sans-malayalam
brew cask install font-noto-sans-mandaic
brew cask install font-noto-sans-meetei-mayek
brew cask install font-noto-sans-mongolian
brew cask install font-noto-sans-myanmar
brew cask install font-noto-sans-n-ko
brew cask install font-noto-sans-new-tai-lue
brew cask install font-noto-sans-ogham
brew cask install font-noto-sans-ol-chiki
brew cask install font-noto-sans-old-italic
brew cask install font-noto-sans-old-persian
brew cask install font-noto-sans-old-south-arabian
brew cask install font-noto-sans-old-turkic
brew cask install font-noto-sans-oriya
brew cask install font-noto-sans-osmanya
brew cask install font-noto-sans-phags-pa
brew cask install font-noto-sans-phoenician
brew cask install font-noto-sans-rejang
brew cask install font-noto-sans-runic
brew cask install font-noto-sans-samaritan
brew cask install font-noto-sans-saurashtra
brew cask install font-noto-sans-shavian
brew cask install font-noto-sans-sinhala
brew cask install font-noto-sans-sundanese
brew cask install font-noto-sans-syloti-nagri
brew cask install font-noto-sans-symbols
brew cask install font-noto-sans-syriac-eastern
brew cask install font-noto-sans-syriac-estrangela
brew cask install font-noto-sans-syriac-western
brew cask install font-noto-sans-tagalog
brew cask install font-noto-sans-tagbanwa
brew cask install font-noto-sans-tai-le
brew cask install font-noto-sans-tai-tham
brew cask install font-noto-sans-tai-viet
brew cask install font-noto-sans-tamil
brew cask install font-noto-sans-telugu
brew cask install font-noto-sans-thaana
brew cask install font-noto-sans-thai
brew cask install font-noto-sans-tibetan
brew cask install font-noto-sans-tifinagh
brew cask install font-noto-sans-ugaritic
brew cask install font-noto-sans-vai
brew cask install font-noto-sans-yi
brew cask install font-noto-sans
brew cask install font-noto-serif-armenian
brew cask install font-noto-serif-georgian
brew cask install font-noto-serif-khmer
brew cask install font-noto-serif-lao
brew cask install font-noto-serif-thai
brew cask install font-noto-serif
brew cask install font-nova-cut
brew cask install font-nova-flat
brew cask install font-nova-mono
brew cask install font-nova-oval
brew cask install font-nova-round
brew cask install font-nova-slim
brew cask install font-nova-square
brew cask install font-numans
brew cask install font-nunito
brew cask install font-nyashi
brew cask install font-ocra
brew cask install font-odor-mean-chey
brew cask install font-office-code-pro
brew cask install font-offside
brew cask install font-old-standard-tt
brew cask install font-oldenburg
brew cask install font-oleo-script-swash-caps
brew cask install font-oleo-script
brew cask install font-open-iconic
brew cask install font-open-sans-condensed
brew cask install font-open-sans-hebrew-condensed
brew cask install font-open-sans-hebrew
brew cask install font-open-sans
brew cask install font-opendyslexic
brew cask install font-oranienbaum
brew cask install font-orbitron
brew cask install font-oregano
brew cask install font-orienta
brew cask install font-original-surfer
brew cask install font-oskiblackfoot
brew cask install font-oskidakelh
brew cask install font-oskidenea
brew cask install font-oskideneb
brew cask install font-oskidenec
brew cask install font-oskidenes
brew cask install font-oskieast
brew cask install font-oskiwest
brew cask install font-oswald
brew cask install font-over-the-rainbow
brew cask install font-overlock-sc
brew cask install font-overlock
brew cask install font-overpass
brew cask install font-ovo
brew cask install font-oxygen-mono
brew cask install font-oxygen
brew cask install font-pacifico
brew cask install font-padauk
brew cask install font-palemonas
brew cask install font-paprika
brew cask install font-parisienne
brew cask install font-passero-one
brew cask install font-passion-one
brew cask install font-pathway-gothic-one
brew cask install font-patrick-hand-sc
brew cask install font-patrick-hand
brew cask install font-patua-one
brew cask install font-paytone-one
brew cask install font-pecita
brew cask install font-penuturesu
brew cask install font-peralta
brew cask install font-permanent-marker
brew cask install font-petit-formal-script
brew cask install font-petrona
brew cask install font-phetsarath
brew cask install font-philosopher
brew cask install font-piedra
brew cask install font-pinyon-script
brew cask install font-pirata-one
brew cask install font-pitabek
brew cask install font-plaster
brew cask install font-play
brew cask install font-playball
brew cask install font-playfair-display-sc
brew cask install font-playfair-display
brew cask install font-podkova
brew cask install font-poetsenone
brew cask install font-poiret-one
brew cask install font-poller-one
brew cask install font-poly
brew cask install font-pompiere
brew cask install font-pontano-sans
brew cask install font-poppins
brew cask install font-port-lligat-sans
brew cask install font-port-lligat-slab
brew cask install font-prata
brew cask install font-preahvihear
brew cask install font-press-start2p
brew cask install font-prime
brew cask install font-prince-valiant
brew cask install font-princess-sofia
brew cask install font-prociono
brew cask install font-profontx
brew cask install font-prosto-one
brew cask install font-pt-mono
brew cask install font-pt-sans
brew cask install font-pt-serif
brew cask install font-puritan
brew cask install font-purple-purse
brew cask install font-qataban
brew cask install font-quando
brew cask install font-quantico
brew cask install font-quattrocento-sans
brew cask install font-quattrocento
brew cask install font-questrial
brew cask install font-quicksand
brew cask install font-quintessential
brew cask install font-quivira
brew cask install font-qwigley
brew cask install font-racing-sans-one
brew cask install font-radley
brew cask install font-rajdhani
brew cask install font-raleway-dots
brew cask install font-raleway
brew cask install font-rambla
brew cask install font-rammetto-one
brew cask install font-ranchers
brew cask install font-rancho
brew cask install font-rationale
brew cask install font-redacted
brew cask install font-reenie-beanie
brew cask install font-revalia
brew cask install font-ribeye-marrow
brew cask install font-ribeye
brew cask install font-ricty-diminished
brew cask install font-righteous
brew cask install font-risque
brew cask install font-roboto-condensed
brew cask install font-roboto-mono-for-powerline
brew cask install font-roboto-mono
brew cask install font-roboto-slab
brew cask install font-roboto
brew cask install font-rochester
brew cask install font-rokkitt
brew cask install font-romanesco
brew cask install font-ropa-sans
brew cask install font-rosario
brew cask install font-rosarivo
brew cask install font-rotinonhsonni-sans
brew cask install font-rotinonhsonni-serif
brew cask install font-rouge-script
brew cask install font-rozha-one
brew cask install font-ruda
brew cask install font-rufina
brew cask install font-ruge-boogie
brew cask install font-ruluko
brew cask install font-rum-raisin
brew cask install font-rupakara
brew cask install font-ruslan-display
brew cask install font-russo-one
brew cask install font-ruthie
brew cask install font-rye
brew cask install font-sacramento
brew cask install font-sadagolthina
brew cask install font-sail
brew cask install font-salsa
brew cask install font-samim
brew cask install font-sanchez
brew cask install font-sancreek
brew cask install font-sarina
brew cask install font-sarpanch
brew cask install font-satisfy
brew cask install font-scada
brew cask install font-scheherazade
brew cask install font-seaweed-script
brew cask install font-seoulhangang
brew cask install font-seoulhangangcondensed
brew cask install font-sevillana
brew cask install font-seymour-one
brew cask install font-shabnam
brew cask install font-shadows-into-light-two
brew cask install font-shadows-into-light
brew cask install font-shanti
brew cask install font-share-tech-mono
brew cask install font-share-tech
brew cask install font-share
brew cask install font-shojumaru
brew cask install font-short-stack
brew cask install font-siemreap
brew cask install font-sigmar-one
brew cask install font-signika-negative
brew cask install font-silent-lips
brew cask install font-simonetta
brew cask install font-sinkin-sans
brew cask install font-sintony
brew cask install font-sirin-stencil
brew cask install font-six-caps
brew cask install font-skranji
brew cask install font-smokum
brew cask install font-smythe
brew cask install font-sniglet
brew cask install font-snippet
brew cask install font-snowburst-one
brew cask install font-sofadi-one
brew cask install font-sofia
brew cask install font-sonsie-one
brew cask install font-sorts-mill-goudy
brew cask install font-source-code-pro-for-powerline
brew cask install font-source-code-pro
brew cask install font-source-han-code-jp
brew cask install font-source-han-sans
brew cask install font-source-sans-pro
brew cask install font-source-serif-pro
brew cask install font-space-mono
brew cask install font-spicy-rice
brew cask install font-spinnaker
brew cask install font-spirax
brew cask install font-squada-one
brew cask install font-stalemate
brew cask install font-stalinist-one
brew cask install font-stardos-stencil
brew cask install font-stint-ultra-condensed
brew cask install font-stint-ultra-expanded
brew cask install font-stoke
brew cask install font-strait
brew cask install font-sue-ellen-francisco
brew cask install font-supermercado-one
brew cask install font-swanky-and-moo-moo
brew cask install font-symbola
brew cask install font-syncopate
brew cask install font-tai-le-valentinium
brew cask install font-takaoex
brew cask install font-tangerine
brew cask install font-taprom
brew cask install font-tauri
brew cask install font-teko
brew cask install font-telex
brew cask install font-tenor-sans
brew cask install font-terminus
brew cask install font-tex-gyre-adventor
brew cask install font-tex-gyre-bonum
brew cask install font-tex-gyre-chorus
brew cask install font-tex-gyre-cursor
brew cask install font-tex-gyre-heros
brew cask install font-tex-gyre-pagella-math
brew cask install font-tex-gyre-pagella
brew cask install font-tex-gyre-schola
brew cask install font-tex-gyre-termes
brew cask install font-text-me-one
brew cask install font-thabit
brew cask install font-the-girl-next-door
brew cask install font-tibetan-machine-uni
brew cask install font-tienne
brew cask install font-tillana
brew cask install font-times-new-roman
brew cask install font-tinos
brew cask install font-titan-one
brew cask install font-titillium-web
brew cask install font-trade-winds
brew cask install font-trebuchet-ms
brew cask install font-trocchi
brew cask install font-trochut
brew cask install font-trykker
brew cask install font-tuffy
brew cask install font-tulpen-one
brew cask install font-twitter-color-emoji
brew cask install font-ubuntu-mono-derivative-powerline
brew cask install font-ubuntu
brew cask install font-uncial-antiqua
brew cask install font-underdog
brew cask install font-unica-one
brew cask install font-unifrakturcook
brew cask install font-unifrakturmaguntia
brew cask install font-unkempt
brew cask install font-unlock
brew cask install font-unna
brew cask install font-vampiro-one
brew cask install font-varela-round
brew cask install font-varela
brew cask install font-vast-shadow
brew cask install font-vazir-code
brew cask install font-vazir
brew cask install font-verdana
brew cask install font-vibur
brew cask install font-vidaloka
brew cask install font-viga
brew cask install font-voces
brew cask install font-volkhov
brew cask install font-vollkorn
brew cask install font-voltaire
brew cask install font-vt323
brew cask install font-waiting-for-the-sunrise
brew cask install font-wakor
brew cask install font-wallpoet
brew cask install font-walter-turncoat
brew cask install font-waltograph
brew cask install font-warnes
brew cask install font-webdings
brew cask install font-wellfleet
brew cask install font-wendy-one
brew cask install font-wenquanyi-micro-hei-lite
brew cask install font-wenquanyi-micro-hei
brew cask install font-wenquanyi-zen-hei
brew cask install font-wire-one
brew cask install font-work-sans
brew cask install font-xits
brew cask install font-yanone-kaffeesatz
brew cask install font-yellowtail
brew cask install font-yeseva-one
brew cask install font-yesteryear
brew cask install font-zeyada
